basePath: /api
definitions:
  request.ApplierRequest:
    properties:
      job_id:
        type: integer
      user_id:
        type: string
    required:
    - job_id
    - user_id
    type: object
  request.CreateJobInput:
    properties:
      category:
        type: string
      company:
        type: string
      description:
        type: string
      image:
        type: string
      location:
        type: string
      salary:
        type: integer
      status:
        type: string
      title:
        type: string
      userId:
        type: string
    required:
    - category
    - company
    - description
    - image
    - location
    - salary
    - status
    - title
    - userId
    type: object
  request.UpdateJobInput:
    properties:
      category:
        type: string
      company:
        type: string
      description:
        type: string
      image:
        type: string
      location:
        type: string
      salary:
        type: integer
      status:
        type: string
      title:
        type: string
    required:
    - category
    - company
    - description
    - image
    - location
    - salary
    - status
    - title
    type: object
  response.WebResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: 103.157.26.181:7426
info:
  contact:
    name: David Afdal
  description: A Jobs management service API in Go using Gin framework.
  title: Gin Go Jobs Service
  version: "1.0"
paths:
  /job:
    get:
      description: Api Enpoint to Get All Data Jobs
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get All Jobs.
      tags:
      - Jobs
    post:
      description: Api Endpoint To Create New Job.
      parameters:
      - description: Data Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.CreateJobInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Create New Job
      tags:
      - Jobs
  /job/{jobId}:
    delete:
      description: Api Endpoint for Delete job.
      parameters:
      - description: param endpoint
        in: path
        name: jobId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Delete job
      tags:
      - Jobs
    get:
      description: Api Enpoint to Get Single Job By Id
      parameters:
      - description: Param Endpoint
        in: path
        name: jobId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get Single Job By Id.
      tags:
      - Jobs
    patch:
      description: Api Endpoint To Update Job
      parameters:
      - description: Param Enpoint
        in: path
        name: jobId
        required: true
        type: integer
      - description: Data Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UpdateJobInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Update Job
      tags:
      - Jobs
  /job/applier/{userId}:
    get:
      description: Api endpoint to get applied job by userId.
      parameters:
      - description: param enpoint
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get Applied Jobs
      tags:
      - Jobs
  /job/apply:
    post:
      description: Api endpoint to apply job.
      parameters:
      - description: data input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.ApplierRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Apply job
      tags:
      - Applicants
  /job/cancel:
    post:
      description: Api Enpoint to cancel apply job.
      parameters:
      - description: data input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.ApplierRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Cancel Apply job
      tags:
      - Applicants
  /job/created/{userId}:
    get:
      description: Api Endpoint To Get Shared Jobs.
      parameters:
      - description: Param Endpoint
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get Shared jobs by userId.
      tags:
      - Jobs
swagger: "2.0"
